### ISSUE TITLE
Why a custom `Decimal` instead of using the built-in type?

### ISSUE THREAD

**Issue by davdroman** [kelvin13/swift-json#63]
```swift
struct Decimal:Codable  
{
    let units:Int 
    let places:Int 
}
```

I'm trying to wrap my head around the need for having a user-defined `Decimal` type for decoding, as opposed to leveraging Swift's own `Decimal` type. It's rather odd to me, a user of the library, having introduce an arbitrary abstraction to be able to decode something into a basic numeric type.

**Comment by kelvin13** [comment]
swift does not have a `Decimal` type, Foundation does, and `JSON` is a Foundation-free framework. (this is very important for keeping binary size down.) 

and the Foundation `Decimal` type is [not compliant with the IEEE standard](https://forums.swift.org/t/notes-on-gsoc-decimal-arithmetic/46789), so its use is limited. `swift-json` defines a very basic decimal type in order to allow users to implement their own lossless decimal handling, if needed. however, in most cases this should not be needed, because [`JSON.Number`](https://swiftinit.org/reference/swift-json/json/json/number) vends a variety of helper APIs to convert itself into basic numeric types.

**Comment by davdroman** [comment]
> swift does not have a `Decimal` type, Foundation does, and `JSON` is a Foundation-free framework. (this is very important for keeping binary size down.)

This is a very noble goal that I wholeheartedly support. However most (99%+) projects out there heavily rely on Foundation and its convenient types. I think a sweet spot could be to include conditional checks like:

```swift
#if canImport(Foundation)
// handy foundation extensions such as native Decimal usage
#endif
```

If this is too heavy-handed for the compiler, perhaps it could appear as as a separate product in the package. Something like `foundation-json`.

I'm only raising this because I believe in your ambition to be the number one JSON decoding/encoding library for Swift. But as a user of this library, I can only think of this goal being attainable by offering the other 99% of your public that are working on something using Foundation the appropriate APIs to do so.

**Comment by davdroman** [comment]
Closing this as I've recently realized how god-awful Foundation's `Decimal` actually is. In hindsight, I must say well done for leaving it up for the developer to decide which type to use. Cheers 🍻

**Comment by kelvin13** [comment]
yep 😂
